export const users = [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      department: "Engineering",
      age: 28,
      salary: 75000,
    },
    {
      id: 2,
      name: "Sarah Smith",
      email: "sarah@example.com",
      department: "HR",
      age: 32,
      salary: 65000,
    },
    {
      id: 3,
      name: "Mike Johnson",
      email: "mike@example.com",
      department: "Finance",
      age: 35,
      salary: 82000,
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily@example.com",
      department: "Engineering",
      age: 26,
      salary: 70000,
    },
    {
      id: 5,
      name: "David Wilson",
      email: "david@example.com",
      department: "Marketing",
      age: 30,
      salary: 68000,
    },
    {
      id: 6,
      name: "Jessica Brown",
      email: "jessica@example.com",
      department: "HR",
      age: 29,
      salary: 62000,
    },
    {
      id: 7,
      name: "Robert Taylor",
      email: "robert@example.com",
      department: "Engineering",
      age: 31,
      salary: 90000,
    },
    {
      id: 8,
      name: "Daniel Anderson",
      email: "daniel@example.com",
      department: "Finance",
      age: 38,
      salary: 95000,
    },
    {
      id: 9,
      name: "Sophia Thomas",
      email: "sophia@example.com",
      department: "Marketing",
      age: 27,
      salary: 61000,
    },
    {
      id: 10,
      name: "James Jackson",
      email: "james@example.com",
      department: "Engineering",
      age: 34,
      salary: 88000,
    },
    {
      id: 11,
      name: "Olivia White",
      email: "olivia@example.com",
      department: "HR",
      age: 25,
      salary: 59000,
    },
    {
      id: 12,
      name: "William Harris",
      email: "william@example.com",
      department: "Finance",
      age: 40,
      salary: 98000,
    },
  ];